### ISSUE TITLE
Chile country boundary incomplete when zoomed out

### ISSUE THREAD

**Issue by mduong7** [MapofLife/species#11]
Country boundary not displaying for middle chunk of Chile when zoomed out to country extent. When zoomed in, boundaries re-appear. Probably because the coast is so complex with so many vertices.

![image](https://cloud.githubusercontent.com/assets/12143665/17305869/d2dc3c5c-57fa-11e6-8554-73789543362e.png)

**Comment by jmalczyk** [comment]
Yes, this is a data problem, not UI. Carto simplifies polygons before feeding them to the tiler (AFAIK). This one is probably t0o detailed to get that done in time for that particular tile. Super complex region polygons like this should get simplified to at least 1km resolution. Moving to MapofLife/database/issues/338
