### ISSUE TITLE
Can't log out from species page

### ISSUE THREAD

**Issue by mduong7** [MapofLife/species#14]
Possibly related to MapofLife/datasets#43?

**Comment by mduong7** [comment]
Actually, can't log off anywhere

**Comment by jmalczyk** [comment]
That is by design.

**Comment by funkycoda** [comment]
Correct. By design. You are owned. 

Just kidding. I'll look into this.

**Comment by funkycoda** [comment]
It looks like the mol.org session is storing some state information that it gets from a previously logged in session based on auth.mol.org. Needs some magic.

 🎩 🐇

**Comment by funkycoda** [comment]
Also, this is a more [mol.org](https://github.com/mapoflife/mol.org) issue than [species](https://github.com/mapoflife/species).
