### ISSUE TITLE
Source display not working for overlapping expert range maps

### ISSUE THREAD

**Issue by mduong7** [MapofLife/species#16]
Example: https://mol.org/species/map/Coronella_girondica

**Comment by villanueval** [comment]
[https://api.mol.org/0.x/species/featuremetadata2](https://api.mol.org/0.x/species/featuremetadata2?datasets=25113706-e901-49ad-abc2-4248604d7765,deae2335-e4b8-4176-aba5-d934cfbb424b,bf4a0b27-9de9-4335-aaab-45ee9baf4bb2,c32622af-dae4-4308-bbb8-f4ecdfc6dfc5&default_uncertainty=20000&lat=44.68427737181225&lng=0.7470703125&max_uncertainty=32000&max_year=2015&min_uncertainty=0&min_year=1970&null_years=false&point_limit=5000&scientificname=Coronella+girondica&zoom=5) is returning an error. The unique id of the row is empty. 

Fixing...

**Comment by villanueval** [comment]
Fixed.
