### ISSUE TITLE
can't search for fish by scientific name

### ISSUE THREAD

**Issue by julieannhart** [MapofLife/species#24]
Search function can't find any fish species by scientific name

**Comment by villanueval** [comment]
Fixed. API for `availabletaxa` was cached with `fishs`.

**Comment by villanueval** [comment]
Seems some species from 'North America Freshwater Fish Range Maps' are missing from `mol_species_master`

Checking...

**Comment by villanueval** [comment]
Re-ingested na_fish. Now its working. Closing issue.
