### ISSUE TITLE
Species appearing outside of selected region appearing during 'Pick Random' search

### ISSUE THREAD

**Issue by mduong7** [MapofLife/species#7]
Example:
https://mol.org/species/map/Opuntia_humifusa?region=vermont

**Comment by villanueval** [comment]
Yeah, this is due to the coarseness of the geohashes we are using (3-chars). I'll be generating 4-chars geohashes to avoid this issue.

**Comment by funkycoda** [comment]
@ljvillanueva, will there be both 3-char and 4-char geohashes or just the 4-char?

**Comment by villanueval** [comment]
1. But these will only appear where necessary. Many will be 2 or 3 chars.

**Comment by jmalczyk** [comment]
This is an API/database issue. Moving to MapofLife/database/issues/339
