### ISSUE TITLE
Source metadata not showing

### ISSUE THREAD

**Issue by mduong7** [MapofLife/species#8]
http://mol.org/species/map/Parkinsonia_aculeata

**Comment by villanueval** [comment]
Seems the dataset metadata modal is expecting a different structure in the json?

http://api.mol.org/0.x/datasets/metadata?id=bdd3c0ac-6c9c-4297-ab47-d2d6dbaadb8a

**Comment by jmalczyk** [comment]
This is fixed, please confirm and close @mduong7

**Comment by mduong7** [comment]
Fix confirmed. Closing.
